databases:
  - name: saacodb
    plan: free
    databaseName: saaco
    user: saaco
domains:
  - saacoapp.com

services:
  - type: web
    plan: free
    name: saaco
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn saaco.asgi:application -k uvicorn.workers.UvicornWorker"

envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: saacodb
      property: connectionString
  - key: SECRET_KEY
    generateValue: true
  - key: WEB_CONCURRENCY
    value: 4